Repository Faiail/IConProgetto, pull requests merged in 2020-01, with the labels that each got.

#2 Aggiunti nuovi task alla progettazione
  README.md
Labels: documentation

#4 Creazione dizionario(malattia:sintomi)
  esempio_AIP/ontology_manager.py
Labels: bug, enhancement

#6 Creata la KB dal dizionario malattie, sintomi
  esempio_AIP/logicProblem.py
  esempio_AIP/ontology_manager.py
Labels: enhancement

#8 Aggiunte funzionalità che creano il modello probabilistico
  esempio_AIP/KB_utlis.py
  esempio_AIP/__pycache__/logicProblem.cpython-36.pyc
  esempio_AIP/__pycache__/prob_utils.cpython-36.pyc
  esempio_AIP/logicProblem.py
  esempio_AIP/prob_utils.py
Labels: enhancement

#10 Creazione di una finestra minimale di dialogo
  esempio_AIP/menu_sintomi.txt
  esempio_AIP/ontology_manager.py
  esempio_AIP/user_interface.py
Labels: enhancement

#12 Aggiunti comandi per gestire la selezione dei sintomi
  esempio_AIP/user_interface.py
Labels: enhancement

#14 Agiunto pulsante Cancel per pulire la console
  esempio_AIP/user_interface.py
Labels: enhancement
