Repository Faiail/IConProgetto, pull requests merged in 2020-02, with the labels that each got.

#16 Reso indipendente locazione del file rispetto al path del pc
  esempio_AIP/KB_utlis.py
  esempio_AIP/__pycache__/KB_utlis.cpython-36.pyc
  esempio_AIP/__pycache__/ontology_manager.cpython-36.pyc
  esempio_AIP/__pycache__/prob_utils.cpython-36.pyc
  esempio_AIP/user_interface.py
Labels: bug, enhancement

#18 Aggiunte funzionalità per visualizzare cosa produce il sistema
  esempio_AIP/__pycache__/KB_utlis.cpython-36.pyc
  esempio_AIP/__pycache__/logicProblem.cpython-36.pyc
  esempio_AIP/user_interface.py
Labels: enhancement

#22 Creato il Report finale
  doc/Report.md
Labels: documentation

#24 Aggiunto paragrafo relativo al manuale utente
  doc/Report.md
  doc/drawings/Esempio_task.PNG
  doc/drawings/Finestra_Home.PNG
Labels: documentation

#26 Aggiunte immagini per il dominio analizzato con esempi
  doc/Report.md
  doc/drawings/Esempio_gerarchia_malattie.png
  doc/drawings/Esempio_gerarchia_sintomi.png
  doc/drawings/Esempio_malattia_sintomi.png
Labels: documentation

#28 Corretto percorso immagine nella sezione manuale utente
  doc/Report.md
Labels: bug

#30 Mostrate a video solo due cifre significative
  src/user_interface.py
Labels: bug

#32 Aggiunta documentazione per lo stile architetturale
  doc/Report.md
Labels: documentation

#34 Modificato errore di lettura
  doc/Report.md
Labels: documentation

#36 Aggiunte tutte le funzionalità per le how question
  src/KB_utlis.py
  src/user_interface.py
Labels: enhancement, help wanted

#40 Aggiunte modifiche al Report per la funzionalità How
  doc/Report.md
  doc/drawings/Esempio_task.PNG
  doc/drawings/Finestra_Home.PNG
  doc/drawings/Spiegazione_malattia.PNG
Labels: documentation
